In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews = ['nice food', 
           'Amazing restaurant',
            'too good',
            'just love it!',
            'will go again',
            'horrible food',
            'never go there',
            'poor service',
            'poor quality',
            'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [12]:
one_hot('amazing restaurant', 50)

[46, 17]

In [13]:
vocab_size = 50
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[35, 36],
 [46, 17],
 [2, 9],
 [21, 41, 14],
 [15, 6, 3],
 [44, 36],
 [46, 6, 20],
 [13, 48],
 [13, 19],
 [19, 1]]

In [15]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[35, 36,  0],
       [46, 17,  0],
       [ 2,  9,  0],
       [21, 41, 14],
       [15,  6,  3],
       [44, 36,  0],
       [46,  6, 20],
       [13, 48,  0],
       [13, 19,  0],
       [19,  1,  0]])

In [16]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length, name='embedding'))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [17]:
X = padded_reviews
y = sentiment

In [18]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              200       
                                                                 
 flatten_1 (Flatten)         (None, 12)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 13        
                                                                 
Total params: 213
Trainable params: 213
Non-trainable params: 0
_________________________________________________________________


In [19]:
model.fit(X, y, epochs=50, verbose=0)

In [20]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 187ms/step - loss: 0.6301 - accuracy: 1.0000


1.0

In [22]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

50

In [23]:
weights[11]

array([ 0.01633421,  0.00547696, -0.01894339,  0.04321101], dtype=float32)

In [24]:
weights[3]

array([ 0.00620537,  0.08681253,  0.05660802, -0.05105251], dtype=float32)